### ISSUE TITLE
Please upgrade versions

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [xsahil03x/fancy_on_boarding#39]
Because image >=3.0.0-nullsafety.0 <3.0.1 depends on xml ^5.0.0-nullsafety.1 and image >=3.0.1 depends on xml ^5.0.0, image >=3.0.0-nullsafety.0 requires xml ^5.0.0-nullsafety.1.
And because flutter_launcher_icons >=0.9.0 depends on image ^3.0.0-nullsafety.0, flutter_launcher_icons >=0.9.0 requires xml ^5.0.0-nullsafety.1.
And because fancy_on_boarding >=1.7.0 depends on flutter_svg ^0.19.1 which depends on xml ^4.2.0, flutter_launcher_icons >=0.9.0 is incompatible with fancy_on_boarding >=1.7.0.
So, because senio_assist depends on both fancy_on_boarding ^1.7.0 and flutter_launcher_icons ^0.9.0, version solving failed.

**Comment by marcuslindemannrohden** [comment]
same here

**Comment by AitoApps** [comment]
same here

**Comment by M1Joe** [comment]
@xsahil03x is this something that you're able to do?  It's a blocker on me upgrading a pretty large app to null safety.  Let us know!

**Comment by xsahil03x** [comment]
Upgraded in:
```dart
fancy_on_boarding: ^1.8.0-nullsafety.0
```
