### ISSUE TITLE
SVG Support

### ISSUE THREAD

**Issue by nikhiljha** [xsahil03x/fancy_on_boarding#8]
https://github.com/nikhiljha/fancy_on_boarding

I made it work with *only* SVGs, but it might be worthwhile to make it work with both.

**Comment by xsahil03x** [comment]
Does it not work with SVG's currently?

**Comment by nikhiljha** [comment]
Nope, flutter doesn't natively support SVGs.

**Comment by medyas** [comment]
i created a pull request that adds SVG support. @xsahil03x can you check it

**Comment by xsahil03x** [comment]
Fixed in #12
